name: "test-nirila-actionn"
description: "test-nirila-actionn"
inputs:
  user-name:
    description: "user name input"
    required: true
    default: "niwaniwa"
runs:
  using: "composite"
  steps:
    - run: go run ${{ github.action_path }}/main.go -userName ${{ inputs.user-name }}
      shell: bash